//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdresTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdresTYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="kodPocztowy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="miejscowosc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="typUlicy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="nazwaUlicy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="numerDomu" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="numerLokalu" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="poczta" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="wojewodztwo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="powiat" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="gmina" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="simc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="terc" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="ulic" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="szerokoscGeograficzna" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dlugoscGeograficzna" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdresTYPE")
public class AdresTYPE {

    @XmlAttribute(name = "kodPocztowy")
    protected String kodPocztowy;
    @XmlAttribute(name = "miejscowosc")
    protected String miejscowosc;
    @XmlAttribute(name = "typUlicy")
    protected String typUlicy;
    @XmlAttribute(name = "nazwaUlicy")
    protected String nazwaUlicy;
    @XmlAttribute(name = "numerDomu")
    protected String numerDomu;
    @XmlAttribute(name = "numerLokalu")
    protected String numerLokalu;
    @XmlAttribute(name = "poczta")
    protected String poczta;
    @XmlAttribute(name = "wojewodztwo")
    protected String wojewodztwo;
    @XmlAttribute(name = "powiat")
    protected String powiat;
    @XmlAttribute(name = "gmina")
    protected String gmina;
    @XmlAttribute(name = "simc")
    protected String simc;
    @XmlAttribute(name = "terc")
    protected String terc;
    @XmlAttribute(name = "ulic")
    protected String ulic;
    @XmlAttribute(name = "szerokoscGeograficzna")
    protected String szerokoscGeograficzna;
    @XmlAttribute(name = "dlugoscGeograficzna")
    protected String dlugoscGeograficzna;

    /**
     * Gets the value of the kodPocztowy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKodPocztowy() {
        return kodPocztowy;
    }

    /**
     * Sets the value of the kodPocztowy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKodPocztowy(String value) {
        this.kodPocztowy = value;
    }

    /**
     * Gets the value of the miejscowosc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiejscowosc() {
        return miejscowosc;
    }

    /**
     * Sets the value of the miejscowosc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiejscowosc(String value) {
        this.miejscowosc = value;
    }

    /**
     * Gets the value of the typUlicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypUlicy() {
        return typUlicy;
    }

    /**
     * Sets the value of the typUlicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypUlicy(String value) {
        this.typUlicy = value;
    }

    /**
     * Gets the value of the nazwaUlicy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwaUlicy() {
        return nazwaUlicy;
    }

    /**
     * Sets the value of the nazwaUlicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwaUlicy(String value) {
        this.nazwaUlicy = value;
    }

    /**
     * Gets the value of the numerDomu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumerDomu() {
        return numerDomu;
    }

    /**
     * Sets the value of the numerDomu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumerDomu(String value) {
        this.numerDomu = value;
    }

    /**
     * Gets the value of the numerLokalu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumerLokalu() {
        return numerLokalu;
    }

    /**
     * Sets the value of the numerLokalu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumerLokalu(String value) {
        this.numerLokalu = value;
    }

    /**
     * Gets the value of the poczta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoczta() {
        return poczta;
    }

    /**
     * Sets the value of the poczta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoczta(String value) {
        this.poczta = value;
    }

    /**
     * Gets the value of the wojewodztwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWojewodztwo() {
        return wojewodztwo;
    }

    /**
     * Sets the value of the wojewodztwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWojewodztwo(String value) {
        this.wojewodztwo = value;
    }

    /**
     * Gets the value of the powiat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowiat() {
        return powiat;
    }

    /**
     * Sets the value of the powiat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowiat(String value) {
        this.powiat = value;
    }

    /**
     * Gets the value of the gmina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGmina() {
        return gmina;
    }

    /**
     * Sets the value of the gmina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGmina(String value) {
        this.gmina = value;
    }

    /**
     * Gets the value of the simc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimc() {
        return simc;
    }

    /**
     * Sets the value of the simc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimc(String value) {
        this.simc = value;
    }

    /**
     * Gets the value of the terc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerc() {
        return terc;
    }

    /**
     * Sets the value of the terc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerc(String value) {
        this.terc = value;
    }

    /**
     * Gets the value of the ulic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUlic() {
        return ulic;
    }

    /**
     * Sets the value of the ulic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUlic(String value) {
        this.ulic = value;
    }

    /**
     * Gets the value of the szerokoscGeograficzna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSzerokoscGeograficzna() {
        return szerokoscGeograficzna;
    }

    /**
     * Sets the value of the szerokoscGeograficzna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSzerokoscGeograficzna(String value) {
        this.szerokoscGeograficzna = value;
    }

    /**
     * Gets the value of the dlugoscGeograficzna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDlugoscGeograficzna() {
        return dlugoscGeograficzna;
    }

    /**
     * Sets the value of the dlugoscGeograficzna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDlugoscGeograficzna(String value) {
        this.dlugoscGeograficzna = value;
    }

}
