//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Apteka" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}AptekaTYPE" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="stanNaDzien" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "apteka"
})
@XmlRootElement(name = "Apteki")
public class Apteki {

    @XmlElement(name = "Apteka")
    protected List<AptekaTYPE> apteka;
    @XmlAttribute(name = "stanNaDzien")
    @XmlSchemaType(name = "anySimpleType")
    protected String stanNaDzien;

    /**
     * Gets the value of the apteka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the apteka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApteka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AptekaTYPE }
     * 
     * 
     */
    public List<AptekaTYPE> getApteka() {
        if (apteka == null) {
            apteka = new ArrayList<AptekaTYPE>();
        }
        return this.apteka;
    }

    /**
     * Gets the value of the stanNaDzien property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStanNaDzien() {
        return stanNaDzien;
    }

    /**
     * Sets the value of the stanNaDzien property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStanNaDzien(String value) {
        this.stanNaDzien = value;
    }

}
