//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AptekaTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AptekaTYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Wlasciciele" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}WlascicieleTYPE" minOccurs="0"/&gt;
 *         &lt;element name="Adres" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}AdresTYPE" minOccurs="0"/&gt;
 *         &lt;element name="KierownikApteki" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}KierownikAptekiTYPE" minOccurs="0"/&gt;
 *         &lt;element name="Zezwolenie" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}ZezwolenieTYPE" minOccurs="0"/&gt;
 *         &lt;element name="ZmianyZezwolen" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}ZmianyZezwolenTYPE" minOccurs="0"/&gt;
 *         &lt;element name="DniPracyApteki" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}DniPracyAptekiType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="adresWWWSprzedazyWysylkowej" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="adresWWWApteki" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dataPonownegoRozpoczeciaDzialalnosciApteki" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataUruchomieniaApteki" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataZaprzestaniaDzialalnosciApteki" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataZawieszeniaDzialalnosciApteki" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataRozpoczeciaSprzedazyWysylkowejApteki" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="emailApteki" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="faxApteki" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rodzaj" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="status" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="numerTelefonu" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="zakresDzialalnosci" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="aptekaCzasowoNieczynna" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AptekaTYPE", propOrder = {
    "wlasciciele",
    "adres",
    "kierownikApteki",
    "zezwolenie",
    "zmianyZezwolen",
    "dniPracyApteki"
})
public class AptekaTYPE {

    @XmlElement(name = "Wlasciciele")
    protected WlascicieleTYPE wlasciciele;
    @XmlElement(name = "Adres")
    protected AdresTYPE adres;
    @XmlElement(name = "KierownikApteki")
    protected KierownikAptekiTYPE kierownikApteki;
    @XmlElement(name = "Zezwolenie")
    protected ZezwolenieTYPE zezwolenie;
    @XmlElement(name = "ZmianyZezwolen")
    protected ZmianyZezwolenTYPE zmianyZezwolen;
    @XmlElement(name = "DniPracyApteki")
    protected DniPracyAptekiType dniPracyApteki;
    @XmlAttribute(name = "adresWWWSprzedazyWysylkowej")
    protected String adresWWWSprzedazyWysylkowej;
    @XmlAttribute(name = "adresWWWApteki")
    protected String adresWWWApteki;
    @XmlAttribute(name = "dataPonownegoRozpoczeciaDzialalnosciApteki")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataPonownegoRozpoczeciaDzialalnosciApteki;
    @XmlAttribute(name = "dataUruchomieniaApteki")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataUruchomieniaApteki;
    @XmlAttribute(name = "dataZaprzestaniaDzialalnosciApteki")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataZaprzestaniaDzialalnosciApteki;
    @XmlAttribute(name = "dataZawieszeniaDzialalnosciApteki")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataZawieszeniaDzialalnosciApteki;
    @XmlAttribute(name = "dataRozpoczeciaSprzedazyWysylkowejApteki")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataRozpoczeciaSprzedazyWysylkowejApteki;
    @XmlAttribute(name = "emailApteki")
    protected String emailApteki;
    @XmlAttribute(name = "faxApteki")
    protected String faxApteki;
    @XmlAttribute(name = "nazwa")
    protected String nazwa;
    @XmlAttribute(name = "rodzaj")
    protected String rodzaj;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "numerTelefonu")
    protected String numerTelefonu;
    @XmlAttribute(name = "zakresDzialalnosci")
    protected String zakresDzialalnosci;
    @XmlAttribute(name = "id")
    protected Integer id;
    @XmlAttribute(name = "aptekaCzasowoNieczynna")
    protected Boolean aptekaCzasowoNieczynna;

    /**
     * Gets the value of the wlasciciele property.
     * 
     * @return
     *     possible object is
     *     {@link WlascicieleTYPE }
     *     
     */
    public WlascicieleTYPE getWlasciciele() {
        return wlasciciele;
    }

    /**
     * Sets the value of the wlasciciele property.
     * 
     * @param value
     *     allowed object is
     *     {@link WlascicieleTYPE }
     *     
     */
    public void setWlasciciele(WlascicieleTYPE value) {
        this.wlasciciele = value;
    }

    /**
     * Gets the value of the adres property.
     * 
     * @return
     *     possible object is
     *     {@link AdresTYPE }
     *     
     */
    public AdresTYPE getAdres() {
        return adres;
    }

    /**
     * Sets the value of the adres property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresTYPE }
     *     
     */
    public void setAdres(AdresTYPE value) {
        this.adres = value;
    }

    /**
     * Gets the value of the kierownikApteki property.
     * 
     * @return
     *     possible object is
     *     {@link KierownikAptekiTYPE }
     *     
     */
    public KierownikAptekiTYPE getKierownikApteki() {
        return kierownikApteki;
    }

    /**
     * Sets the value of the kierownikApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link KierownikAptekiTYPE }
     *     
     */
    public void setKierownikApteki(KierownikAptekiTYPE value) {
        this.kierownikApteki = value;
    }

    /**
     * Gets the value of the zezwolenie property.
     * 
     * @return
     *     possible object is
     *     {@link ZezwolenieTYPE }
     *     
     */
    public ZezwolenieTYPE getZezwolenie() {
        return zezwolenie;
    }

    /**
     * Sets the value of the zezwolenie property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZezwolenieTYPE }
     *     
     */
    public void setZezwolenie(ZezwolenieTYPE value) {
        this.zezwolenie = value;
    }

    /**
     * Gets the value of the zmianyZezwolen property.
     * 
     * @return
     *     possible object is
     *     {@link ZmianyZezwolenTYPE }
     *     
     */
    public ZmianyZezwolenTYPE getZmianyZezwolen() {
        return zmianyZezwolen;
    }

    /**
     * Sets the value of the zmianyZezwolen property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZmianyZezwolenTYPE }
     *     
     */
    public void setZmianyZezwolen(ZmianyZezwolenTYPE value) {
        this.zmianyZezwolen = value;
    }

    /**
     * Gets the value of the dniPracyApteki property.
     * 
     * @return
     *     possible object is
     *     {@link DniPracyAptekiType }
     *     
     */
    public DniPracyAptekiType getDniPracyApteki() {
        return dniPracyApteki;
    }

    /**
     * Sets the value of the dniPracyApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link DniPracyAptekiType }
     *     
     */
    public void setDniPracyApteki(DniPracyAptekiType value) {
        this.dniPracyApteki = value;
    }

    /**
     * Gets the value of the adresWWWSprzedazyWysylkowej property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresWWWSprzedazyWysylkowej() {
        return adresWWWSprzedazyWysylkowej;
    }

    /**
     * Sets the value of the adresWWWSprzedazyWysylkowej property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresWWWSprzedazyWysylkowej(String value) {
        this.adresWWWSprzedazyWysylkowej = value;
    }

    /**
     * Gets the value of the adresWWWApteki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresWWWApteki() {
        return adresWWWApteki;
    }

    /**
     * Sets the value of the adresWWWApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresWWWApteki(String value) {
        this.adresWWWApteki = value;
    }

    /**
     * Gets the value of the dataPonownegoRozpoczeciaDzialalnosciApteki property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataPonownegoRozpoczeciaDzialalnosciApteki() {
        return dataPonownegoRozpoczeciaDzialalnosciApteki;
    }

    /**
     * Sets the value of the dataPonownegoRozpoczeciaDzialalnosciApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataPonownegoRozpoczeciaDzialalnosciApteki(XMLGregorianCalendar value) {
        this.dataPonownegoRozpoczeciaDzialalnosciApteki = value;
    }

    /**
     * Gets the value of the dataUruchomieniaApteki property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataUruchomieniaApteki() {
        return dataUruchomieniaApteki;
    }

    /**
     * Sets the value of the dataUruchomieniaApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataUruchomieniaApteki(XMLGregorianCalendar value) {
        this.dataUruchomieniaApteki = value;
    }

    /**
     * Gets the value of the dataZaprzestaniaDzialalnosciApteki property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataZaprzestaniaDzialalnosciApteki() {
        return dataZaprzestaniaDzialalnosciApteki;
    }

    /**
     * Sets the value of the dataZaprzestaniaDzialalnosciApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataZaprzestaniaDzialalnosciApteki(XMLGregorianCalendar value) {
        this.dataZaprzestaniaDzialalnosciApteki = value;
    }

    /**
     * Gets the value of the dataZawieszeniaDzialalnosciApteki property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataZawieszeniaDzialalnosciApteki() {
        return dataZawieszeniaDzialalnosciApteki;
    }

    /**
     * Sets the value of the dataZawieszeniaDzialalnosciApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataZawieszeniaDzialalnosciApteki(XMLGregorianCalendar value) {
        this.dataZawieszeniaDzialalnosciApteki = value;
    }

    /**
     * Gets the value of the dataRozpoczeciaSprzedazyWysylkowejApteki property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataRozpoczeciaSprzedazyWysylkowejApteki() {
        return dataRozpoczeciaSprzedazyWysylkowejApteki;
    }

    /**
     * Sets the value of the dataRozpoczeciaSprzedazyWysylkowejApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataRozpoczeciaSprzedazyWysylkowejApteki(XMLGregorianCalendar value) {
        this.dataRozpoczeciaSprzedazyWysylkowejApteki = value;
    }

    /**
     * Gets the value of the emailApteki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailApteki() {
        return emailApteki;
    }

    /**
     * Sets the value of the emailApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailApteki(String value) {
        this.emailApteki = value;
    }

    /**
     * Gets the value of the faxApteki property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFaxApteki() {
        return faxApteki;
    }

    /**
     * Sets the value of the faxApteki property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFaxApteki(String value) {
        this.faxApteki = value;
    }

    /**
     * Gets the value of the nazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwa() {
        return nazwa;
    }

    /**
     * Sets the value of the nazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwa(String value) {
        this.nazwa = value;
    }

    /**
     * Gets the value of the rodzaj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRodzaj() {
        return rodzaj;
    }

    /**
     * Sets the value of the rodzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRodzaj(String value) {
        this.rodzaj = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the numerTelefonu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumerTelefonu() {
        return numerTelefonu;
    }

    /**
     * Sets the value of the numerTelefonu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumerTelefonu(String value) {
        this.numerTelefonu = value;
    }

    /**
     * Gets the value of the zakresDzialalnosci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZakresDzialalnosci() {
        return zakresDzialalnosci;
    }

    /**
     * Sets the value of the zakresDzialalnosci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZakresDzialalnosci(String value) {
        this.zakresDzialalnosci = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setId(Integer value) {
        this.id = value;
    }

    /**
     * Gets the value of the aptekaCzasowoNieczynna property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAptekaCzasowoNieczynna() {
        return aptekaCzasowoNieczynna;
    }

    /**
     * Sets the value of the aptekaCzasowoNieczynna property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAptekaCzasowoNieczynna(Boolean value) {
        this.aptekaCzasowoNieczynna = value;
    }

}
