//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for DzienPracyType complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DzienPracyType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute name="dzienTygodnia" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="calodobowa" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="otwartaOd" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="otwartaDo" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DzienPracyType", propOrder = {
    "value"
})
public class DzienPracyType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "dzienTygodnia", required = true)
    protected String dzienTygodnia;
    @XmlAttribute(name = "calodobowa", required = true)
    protected String calodobowa;
    @XmlAttribute(name = "otwartaOd")
    protected String otwartaOd;
    @XmlAttribute(name = "otwartaDo")
    protected String otwartaDo;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the dzienTygodnia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDzienTygodnia() {
        return dzienTygodnia;
    }

    /**
     * Sets the value of the dzienTygodnia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDzienTygodnia(String value) {
        this.dzienTygodnia = value;
    }

    /**
     * Gets the value of the calodobowa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalodobowa() {
        return calodobowa;
    }

    /**
     * Sets the value of the calodobowa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalodobowa(String value) {
        this.calodobowa = value;
    }

    /**
     * Gets the value of the otwartaOd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtwartaOd() {
        return otwartaOd;
    }

    /**
     * Sets the value of the otwartaOd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtwartaOd(String value) {
        this.otwartaOd = value;
    }

    /**
     * Gets the value of the otwartaDo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtwartaDo() {
        return otwartaDo;
    }

    /**
     * Sets the value of the otwartaDo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtwartaDo(String value) {
        this.otwartaDo = value;
    }

}
