//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mita.pharmaciesmarket.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DniPracyAptekiTypeDniPracyDzienPracy_QNAME = new QName("http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0", "DzienPracy");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mita.pharmaciesmarket.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DniPracyAptekiType }
     * 
     */
    public DniPracyAptekiType createDniPracyAptekiType() {
        return new DniPracyAptekiType();
    }

    /**
     * Create an instance of {@link Apteki }
     * 
     */
    public Apteki createApteki() {
        return new Apteki();
    }

    /**
     * Create an instance of {@link AptekaTYPE }
     * 
     */
    public AptekaTYPE createAptekaTYPE() {
        return new AptekaTYPE();
    }

    /**
     * Create an instance of {@link WlascicieleTYPE }
     * 
     */
    public WlascicieleTYPE createWlascicieleTYPE() {
        return new WlascicieleTYPE();
    }

    /**
     * Create an instance of {@link WlascicielTYPE }
     * 
     */
    public WlascicielTYPE createWlascicielTYPE() {
        return new WlascicielTYPE();
    }

    /**
     * Create an instance of {@link AdresTYPE }
     * 
     */
    public AdresTYPE createAdresTYPE() {
        return new AdresTYPE();
    }

    /**
     * Create an instance of {@link ZezwolenieTYPE }
     * 
     */
    public ZezwolenieTYPE createZezwolenieTYPE() {
        return new ZezwolenieTYPE();
    }

    /**
     * Create an instance of {@link KierownikAptekiTYPE }
     * 
     */
    public KierownikAptekiTYPE createKierownikAptekiTYPE() {
        return new KierownikAptekiTYPE();
    }

    /**
     * Create an instance of {@link ZmianyZezwolenTYPE }
     * 
     */
    public ZmianyZezwolenTYPE createZmianyZezwolenTYPE() {
        return new ZmianyZezwolenTYPE();
    }

    /**
     * Create an instance of {@link ZmianaTYPE }
     * 
     */
    public ZmianaTYPE createZmianaTYPE() {
        return new ZmianaTYPE();
    }

    /**
     * Create an instance of {@link DzienPracyType }
     * 
     */
    public DzienPracyType createDzienPracyType() {
        return new DzienPracyType();
    }

    /**
     * Create an instance of {@link DniPracyAptekiType.DniPracy }
     * 
     */
    public DniPracyAptekiType.DniPracy createDniPracyAptekiTypeDniPracy() {
        return new DniPracyAptekiType.DniPracy();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DzienPracyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DzienPracyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0", name = "DzienPracy", scope = DniPracyAptekiType.DniPracy.class)
    public JAXBElement<DzienPracyType> createDniPracyAptekiTypeDniPracyDzienPracy(DzienPracyType value) {
        return new JAXBElement<DzienPracyType>(_DniPracyAptekiTypeDniPracyDzienPracy_QNAME, DzienPracyType.class, DniPracyAptekiType.DniPracy.class, value);
    }

}
