//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WlascicielTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WlascicielTYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Adres" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}AdresTYPE" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="formaPrawna" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="imie" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="krs" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="nazwisko" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="nip" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="regon" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WlascicielTYPE", propOrder = {
    "adres"
})
public class WlascicielTYPE {

    @XmlElement(name = "Adres")
    protected AdresTYPE adres;
    @XmlAttribute(name = "formaPrawna")
    protected String formaPrawna;
    @XmlAttribute(name = "imie")
    protected String imie;
    @XmlAttribute(name = "krs")
    protected String krs;
    @XmlAttribute(name = "nazwa")
    protected String nazwa;
    @XmlAttribute(name = "nazwisko")
    protected String nazwisko;
    @XmlAttribute(name = "nip")
    protected String nip;
    @XmlAttribute(name = "regon")
    protected String regon;

    /**
     * Gets the value of the adres property.
     * 
     * @return
     *     possible object is
     *     {@link AdresTYPE }
     *     
     */
    public AdresTYPE getAdres() {
        return adres;
    }

    /**
     * Sets the value of the adres property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresTYPE }
     *     
     */
    public void setAdres(AdresTYPE value) {
        this.adres = value;
    }

    /**
     * Gets the value of the formaPrawna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormaPrawna() {
        return formaPrawna;
    }

    /**
     * Sets the value of the formaPrawna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormaPrawna(String value) {
        this.formaPrawna = value;
    }

    /**
     * Gets the value of the imie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImie() {
        return imie;
    }

    /**
     * Sets the value of the imie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImie(String value) {
        this.imie = value;
    }

    /**
     * Gets the value of the krs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKrs() {
        return krs;
    }

    /**
     * Sets the value of the krs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKrs(String value) {
        this.krs = value;
    }

    /**
     * Gets the value of the nazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwa() {
        return nazwa;
    }

    /**
     * Sets the value of the nazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwa(String value) {
        this.nazwa = value;
    }

    /**
     * Gets the value of the nazwisko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwisko() {
        return nazwisko;
    }

    /**
     * Sets the value of the nazwisko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwisko(String value) {
        this.nazwisko = value;
    }

    /**
     * Gets the value of the nip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNip() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNip(String value) {
        this.nip = value;
    }

    /**
     * Gets the value of the regon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegon() {
        return regon;
    }

    /**
     * Sets the value of the regon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegon(String value) {
        this.regon = value;
    }

}
