//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WlascicieleTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WlascicieleTYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Adres" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}AdresTYPE" minOccurs="0"/&gt;
 *         &lt;element name="Wlasciciel" type="{http://rejestrymedyczne.csioz.gov.pl/ra/eksport-danych-v1.0}WlascicielTYPE" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="nazwaSpolkiCywilnej" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="nip" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="regon" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WlascicieleTYPE", propOrder = {
    "adres",
    "wlasciciel"
})
public class WlascicieleTYPE {

    @XmlElement(name = "Adres")
    protected AdresTYPE adres;
    @XmlElement(name = "Wlasciciel")
    protected List<WlascicielTYPE> wlasciciel;
    @XmlAttribute(name = "nazwaSpolkiCywilnej")
    protected String nazwaSpolkiCywilnej;
    @XmlAttribute(name = "nip")
    protected String nip;
    @XmlAttribute(name = "regon")
    protected String regon;

    /**
     * Gets the value of the adres property.
     * 
     * @return
     *     possible object is
     *     {@link AdresTYPE }
     *     
     */
    public AdresTYPE getAdres() {
        return adres;
    }

    /**
     * Sets the value of the adres property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdresTYPE }
     *     
     */
    public void setAdres(AdresTYPE value) {
        this.adres = value;
    }

    /**
     * Gets the value of the wlasciciel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wlasciciel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWlasciciel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WlascicielTYPE }
     * 
     * 
     */
    public List<WlascicielTYPE> getWlasciciel() {
        if (wlasciciel == null) {
            wlasciciel = new ArrayList<WlascicielTYPE>();
        }
        return this.wlasciciel;
    }

    /**
     * Gets the value of the nazwaSpolkiCywilnej property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwaSpolkiCywilnej() {
        return nazwaSpolkiCywilnej;
    }

    /**
     * Sets the value of the nazwaSpolkiCywilnej property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwaSpolkiCywilnej(String value) {
        this.nazwaSpolkiCywilnej = value;
    }

    /**
     * Gets the value of the nip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNip() {
        return nip;
    }

    /**
     * Sets the value of the nip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNip(String value) {
        this.nip = value;
    }

    /**
     * Gets the value of the regon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegon() {
        return regon;
    }

    /**
     * Sets the value of the regon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegon(String value) {
        this.regon = value;
    }

}
