//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ZezwolenieTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZezwolenieTYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="dataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataUprawomocnieniaZezwolenia" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataUprawomocnieniaCofnieciaWygaszeniaZezwolenia" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataCofnieciaZezwolenia" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataWydania" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="dataWygaszeniaZezwolenia" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *       &lt;attribute name="nrZezwolenia" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="organWydajacy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="rodzajZezwolenia" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="sygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="terminWaznosci" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="uwagiZezwolenia" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZezwolenieTYPE")
public class ZezwolenieTYPE {

    @XmlAttribute(name = "dataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia;
    @XmlAttribute(name = "dataUprawomocnieniaZezwolenia")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataUprawomocnieniaZezwolenia;
    @XmlAttribute(name = "dataUprawomocnieniaCofnieciaWygaszeniaZezwolenia")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataUprawomocnieniaCofnieciaWygaszeniaZezwolenia;
    @XmlAttribute(name = "dataCofnieciaZezwolenia")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataCofnieciaZezwolenia;
    @XmlAttribute(name = "dataWydania")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataWydania;
    @XmlAttribute(name = "dataWygaszeniaZezwolenia")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataWygaszeniaZezwolenia;
    @XmlAttribute(name = "nrZezwolenia")
    protected String nrZezwolenia;
    @XmlAttribute(name = "organWydajacy")
    protected String organWydajacy;
    @XmlAttribute(name = "rodzajZezwolenia")
    protected String rodzajZezwolenia;
    @XmlAttribute(name = "sygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia")
    protected String sygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia;
    @XmlAttribute(name = "terminWaznosci")
    protected String terminWaznosci;
    @XmlAttribute(name = "uwagiZezwolenia")
    protected String uwagiZezwolenia;

    /**
     * Gets the value of the dataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia() {
        return dataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia;
    }

    /**
     * Sets the value of the dataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia(XMLGregorianCalendar value) {
        this.dataNadaniaRygoruNatychmiastowejWykonalnosciCofniecia = value;
    }

    /**
     * Gets the value of the dataUprawomocnieniaZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataUprawomocnieniaZezwolenia() {
        return dataUprawomocnieniaZezwolenia;
    }

    /**
     * Sets the value of the dataUprawomocnieniaZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataUprawomocnieniaZezwolenia(XMLGregorianCalendar value) {
        this.dataUprawomocnieniaZezwolenia = value;
    }

    /**
     * Gets the value of the dataUprawomocnieniaCofnieciaWygaszeniaZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataUprawomocnieniaCofnieciaWygaszeniaZezwolenia() {
        return dataUprawomocnieniaCofnieciaWygaszeniaZezwolenia;
    }

    /**
     * Sets the value of the dataUprawomocnieniaCofnieciaWygaszeniaZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataUprawomocnieniaCofnieciaWygaszeniaZezwolenia(XMLGregorianCalendar value) {
        this.dataUprawomocnieniaCofnieciaWygaszeniaZezwolenia = value;
    }

    /**
     * Gets the value of the dataCofnieciaZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataCofnieciaZezwolenia() {
        return dataCofnieciaZezwolenia;
    }

    /**
     * Sets the value of the dataCofnieciaZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataCofnieciaZezwolenia(XMLGregorianCalendar value) {
        this.dataCofnieciaZezwolenia = value;
    }

    /**
     * Gets the value of the dataWydania property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataWydania() {
        return dataWydania;
    }

    /**
     * Sets the value of the dataWydania property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataWydania(XMLGregorianCalendar value) {
        this.dataWydania = value;
    }

    /**
     * Gets the value of the dataWygaszeniaZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataWygaszeniaZezwolenia() {
        return dataWygaszeniaZezwolenia;
    }

    /**
     * Sets the value of the dataWygaszeniaZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataWygaszeniaZezwolenia(XMLGregorianCalendar value) {
        this.dataWygaszeniaZezwolenia = value;
    }

    /**
     * Gets the value of the nrZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrZezwolenia() {
        return nrZezwolenia;
    }

    /**
     * Sets the value of the nrZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrZezwolenia(String value) {
        this.nrZezwolenia = value;
    }

    /**
     * Gets the value of the organWydajacy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganWydajacy() {
        return organWydajacy;
    }

    /**
     * Sets the value of the organWydajacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganWydajacy(String value) {
        this.organWydajacy = value;
    }

    /**
     * Gets the value of the rodzajZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRodzajZezwolenia() {
        return rodzajZezwolenia;
    }

    /**
     * Sets the value of the rodzajZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRodzajZezwolenia(String value) {
        this.rodzajZezwolenia = value;
    }

    /**
     * Gets the value of the sygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia() {
        return sygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia;
    }

    /**
     * Sets the value of the sygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia(String value) {
        this.sygnaturaSprawyDlaCofnieciaWygaszeniaZezwolenia = value;
    }

    /**
     * Gets the value of the terminWaznosci property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerminWaznosci() {
        return terminWaznosci;
    }

    /**
     * Sets the value of the terminWaznosci property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerminWaznosci(String value) {
        this.terminWaznosci = value;
    }

    /**
     * Gets the value of the uwagiZezwolenia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUwagiZezwolenia() {
        return uwagiZezwolenia;
    }

    /**
     * Sets the value of the uwagiZezwolenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUwagiZezwolenia(String value) {
        this.uwagiZezwolenia = value;
    }

}
