//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2018.06.30 at 11:31:33 AM CEST 
//


package com.mita.pharmaciesmarket.model.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ZmianaTYPE complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ZmianaTYPE"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="nrDokumentu" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="dataWydania" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ZmianaTYPE")
public class ZmianaTYPE {

    @XmlAttribute(name = "nrDokumentu")
    protected String nrDokumentu;
    @XmlAttribute(name = "dataWydania")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dataWydania;

    /**
     * Gets the value of the nrDokumentu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNrDokumentu() {
        return nrDokumentu;
    }

    /**
     * Sets the value of the nrDokumentu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNrDokumentu(String value) {
        this.nrDokumentu = value;
    }

    /**
     * Gets the value of the dataWydania property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataWydania() {
        return dataWydania;
    }

    /**
     * Sets the value of the dataWydania property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataWydania(XMLGregorianCalendar value) {
        this.dataWydania = value;
    }

}
